language: dart
dart:
  - 2.18.0
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone --depth 1 --branch 3.0.5 https://github.com/flutter/flutter.git
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
  - cp .env.example .env
script:
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
