name: fyx
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  provider: ^4.3.1
  meta: ^1.1.8
  dio: ^3.0.9
  flutter_sticky_header: ^0.4.5
  html: ^0.14.0+3
  flutter_html: 1.0.2
  shared_preferences: ^0.5.8
  fluttertoast: ^7.1.1
  html_unescape: ^1.0.2
  cached_network_image: ^2.2.0+1
  carousel_slider: ^1.4.0
  device_info: ^0.4.2+7
  package_info: ^0.4.1
  url_launcher: ^5.7.5
  photo_view:
    git:
      url: https://github.com/fireslime/photo_view.git
      ref: master
  auto_size_text: ^2.1.0
  image_picker:
    git:
      url: https://github.com/knaeckeKami/plugins.git
      path: packages/image_picker/image_picker
  path: ^1.6.4
  image: ^2.1.14
  async: ^2.4.1
  chewie: ^0.9.10
  video_player: ^0.10.11+2
  flutter_cupertino_settings: ^0.3.1
  flutter_markdown: ^0.4.2
  http: ^0.12.2
  share: ^0.6.5
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  firebase_analytics: ^6.0.0
  sentry: any
  flutter_dotenv: ^2.1.0
  firebase_messaging: ^7.0.2
  flutter_highlight: ^0.6.0
  image_gallery_saver: ^1.6.7

  # Dart-lang core plugins 👇
  http_parser: ^3.1.4
  mime: ^0.9.7

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  # https://github.com/dnfield/flutter_svg/issues/368#issuecomment-650297001
  # https://github.com/Sub6Resources/flutter_html/issues/358
  flutter_svg: ^0.19.0

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.0
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - logo.png
    - tutorial-1.png
    - tutorial-2.png
    - tutorial-3.png
    - tutorial-4.png
    - travolta.gif

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/JetBrainsMono-SemiLight.ttf
